services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: smard_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - integrate

networks:
  integrate:
    external: true